name: movies_interview_task
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  build_runner: ^2.3.3
  connectivity_plus: ^3.0.6
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.5
  freezed: ^2.3.3
  freezed_annotation: ^2.2.0
  go_router: ^7.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  retrofit_generator: ^6.0.0+3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/

  fonts:
    - family: FilsonPro
      fonts:
        - asset: assets/fonts/FilsonProRegular.otf
          weight: 400 #normal
        - asset: assets/fonts/FilsonProRegular.otf
          weight: 500 #bold
        - asset: assets/fonts/FilsonProRegular.otf
          weight: 700 #bold2


    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.otf
          weight: 700 #bold